import type { Roadmap } from '@/roadmap/types';

export const TD_ROADMAP: Roadmap = {
  project: '터미널 대시보드 (Terminal Dashboard)',
  version: 1,
  updated: '2026-04-21',
  vision:
    'Electron + xterm.js + node-pty 로컬 터미널 앱. 맥북-아이맥 멀티호스트 환경에서 "어느 터미널이 어느 머신인지" 3초 안에 판별되는 UX. 내장 웹 프리뷰 모니터로 iframe 대체 없이 실제 Chromium 조작.',
  currentPhaseId: 'p3-deploy',
  phases: [
    {
      id: 'p1-mvp-local',
      title: 'v1.0.6 — 로컬 터미널 MVP',
      status: 'done',
      start: '2026-02-01',
      end: '2026-03-25',
      summary: 'xterm.js + node-pty로 로컬 zsh 세션. 탭·미니 대시보드·시스템 통계 카드.',
      goal: 'Electron 앱 하나로 터미널 N개 + 머신 상태(CPU/RAM/디스크) 모니터링.',
      items: [
        { title: 'Electron + xterm.js 셋업', status: 'done' },
        { title: 'node-pty로 로컬 zsh 세션', status: 'done' },
        { title: '탭 바 + 터미널 N개 동시 운영', status: 'done' },
        { title: 'os.cpus / freemem / df -h 기반 시스템 통계 카드', status: 'done' },
        { title: '미니 대시보드 (터미널별 상태 카드)', status: 'done' },
        { title: 'td-preview MCP 내장 웹 프리뷰 모니터', status: 'done' },
      ],
    },
    {
      id: 'p2-multihost',
      title: 'v1.1.0 — 멀티호스트 UX (Phase 1·2·3)',
      status: 'done',
      start: '2026-03-26',
      end: '2026-04-19',
      summary: '"맥북 vs 아이맥" 3초 판별. 호스트 컬러바·아이콘·약어 라벨·시스템 카드 분리.',
      goal: '호스트 식별 요소가 UI 모든 레이어(탭바·헤더·미니카드·시스템카드)에 일관 노출.',
      items: [
        { title: 'Host 엔티티 데이터 모델 (id·label·color·icon·connection)', status: 'done' },
        { title: 'Terminal → hostId 연결', status: 'done' },
        { title: '탭바에 호스트 약어 라벨 + 컬러 바', status: 'done' },
        { title: '터미널 헤더에 호스트 아이콘', status: 'done' },
        { title: '미니 카드에 호스트 표식', status: 'done' },
        { title: '시스템 카드 머신별 분리 (맥북·아이맥 동시)', status: 'done' },
        { title: '상태 dot 세분화 (connected/busy/disconnected/ssh-fail)', status: 'done' },
        { title: 'v1.1.0 ad-hoc 서명 빌드 + dmg 생성', status: 'done' },
      ],
    },
    {
      id: 'p3-deploy',
      title: '배포 — v1.0.6 제거 + v1.1.0 설치',
      status: 'in-progress',
      target: '2026-04-25',
      summary: '현재 사용자는 v1.1.0 빌드만 끝낸 상태. 기존 v1.0.6 제거 후 /Applications에 설치.',
      goal: '맥북에 v1.1.0만 살아있고 xattr 차단 해제되어 정상 실행.',
      items: [
        { title: 'v1.0.6 프로세스 완전 종료 확인', status: 'todo' },
        { title: '/Applications/Terminal Dashboard.app 제거', status: 'todo' },
        { title: 'v1.1.0.app을 /Applications에 복사', status: 'todo' },
        { title: 'xattr -cr로 ad-hoc 서명 차단 해제', status: 'todo' },
        { title: '첫 실행 확인 + dmg 정리', status: 'todo' },
        { title: '아이맥에도 v1.1.0 설치 (원격 호스트 연결용)', status: 'todo' },
      ],
    },
    {
      id: 'p4-next-improvements',
      title: '다음 개선 후보 (우선순위순)',
      status: 'planned',
      target: '2026-06-30',
      summary: 'NEXT_SESSION.md에 나열된 우선순위 개선들. 하나씩 선택해 진행.',
      goal: '배포 안정화 후 UX/기능 보강.',
      items: [
        { title: 'A. ⌘K 커맨드 팔레트 (터미널 전환·탭 생성·명령 실행)', status: 'todo' },
        { title: 'B. 탭 활동 표시 (백그라운드 터미널 알림 dot)', status: 'todo' },
        { title: 'C. 호스트 레지스트리 + Settings UI (SSH 키 관리 · 호스트 추가)', status: 'todo' },
        { title: 'D. 환경 태그 (dev/staging/prod 색상 구분)', status: 'todo' },
        { title: 'E. 시스템 카드 스파크라인 (CPU/RAM 추이)', status: 'todo' },
        { title: 'F. 미니 대시보드 접기/펼치기 토글', status: 'todo' },
        { title: '(보류) 세션 복원 — xterm.js 버퍼 영속화 복잡도 높음', status: 'skipped', note: '후순위' },
      ],
    },
    {
      id: 'p5-future',
      title: 'Future — 원격/공유 확장',
      status: 'planned',
      target: '2026-10-31',
      summary: '단일 유저 로컬 앱 → 팀 공유·원격 접속 고도화.',
      goal: '아이맥뿐 아니라 팀 서버·외부 원격 셸까지 한 앱에서 관리.',
      items: [
        { title: 'SSH 연결 안정성 (재접속·키 검증)', status: 'todo' },
        { title: 'tmux·zellij 세션 attach/detach 통합', status: 'todo' },
        { title: '팀원과 터미널 공유 (screenshare 스타일)', status: 'todo' },
      ],
    },
  ],
  decisions: [
    {
      date: '2026-04-19',
      title: '멀티호스트 UX를 컬러+아이콘+약어 3중 신호로',
      why: '제목만으로는 3초 판별 불가. 색(accent bar) + 아이콘(laptop/desktop/server) + 약어(MB/iMac) 3중이면 최소한 하나는 시야에 잡힘.',
      alt: '제목에 호스트명 prefix만 추가 — 기각. 시각 신호 부족.',
    },
    {
      date: '2026-03-01',
      title: '내장 웹 프리뷰 모니터 + td-preview MCP',
      why: 'Claude가 외부 Playwright로 브라우저 조작하면 iframe 제약·창 전환 비용 큼. 앱 내부에 Chromium BrowserView 띄우고 MCP로 직접 조작하면 단일 앱에서 완결.',
      alt: '외부 Playwright MCP — 보류. td 작업 중에는 td-preview 우선.',
    },
  ],
  openQuestions: [
    '⌘K 커맨드 팔레트 — 명령 알아서 추천(VS Code 스타일) vs 카테고리별 리스트 중 어느 쪽?',
    'SSH 키 관리를 앱 내부 UI로 할지, ~/.ssh/config 그대로 읽을지?',
    '세션 복원 — 버퍼 영속화 필요한가, 아니면 탭 구성만 복원?',
  ],
  risks: [
    {
      title: 'ad-hoc 서명 빌드의 macOS Gatekeeper 차단',
      mitigation: '매 배포 시 xattr -cr 절차 문서화. 장기적으로 Apple Developer 유료 계정 + notarization.',
      severity: 'med',
    },
    {
      title: 'node-pty ABI 호환성 (Electron 버전 업그레이드 시)',
      mitigation: 'electron-rebuild 자동화 스크립트. NEXT_SESSION.md에 복구 절차 명시됨.',
      severity: 'low',
    },
  ],
};
