import type { ERD } from '@/erd/types';

export const ARC_V2_ERD: ERD = {
  project: 'ARC V2',
  version: 1,
  updated: '2026-04-21',
  vision:
    'Express + better-sqlite3 백엔드 데이터 모델. 에이전트 레지스트리 + 세션/메시지 + 스쿼드/태스크 + 도메인 규칙 + 피드백 누적.',
  canvas: { width: 1440, height: 760 },
  groups: [
    { id: 'agent',  name: '에이전트',   color: '#1e3a8a', accentBg: '#eff6ff', accentText: '#1e3a8a' },
    { id: 'chat',   name: '대화',       color: '#16a34a', accentBg: '#ecfdf5', accentText: '#15803d' },
    { id: 'ops',    name: '운영',       color: '#d97706', accentBg: '#fffbeb', accentText: '#b45309' },
  ],
  entities: [
    {
      id: 'agents', name: 'agents', label: '에이전트', groupId: 'agent', icon: 'UserPlus',
      description: '등록된 에이전트. MCP를 통해 외부 봇들이 자기 자신을 등록.',
      x: 60, y: 80, width: 240,
      fields: [
        { name: 'id', type: 'text', pk: true },
        { name: 'name', type: 'text' },
        { name: 'type', type: 'enum' },
        { name: 'status', type: 'enum', note: 'online | offline | idle' },
        { name: 'metadata', type: 'json' },
        { name: 'last_heartbeat', type: 'timestamp' },
      ],
    },
    {
      id: 'sessions', name: 'sessions', label: '세션', groupId: 'chat', icon: 'FileText',
      description: '에이전트와의 대화 세션 (채널=Telegram/Slack/내부).',
      x: 400, y: 80, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'agent_id', type: 'text', fk: { entity: 'agents' } },
        { name: 'channel', type: 'enum' },
        { name: 'created_at', type: 'timestamp' },
      ],
    },
    {
      id: 'messages', name: 'messages', label: '메시지', groupId: 'chat', icon: 'FileText',
      description: '세션 내 개별 메시지 + 이모지 리액션.',
      x: 740, y: 80, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'session_id', type: 'uuid', fk: { entity: 'sessions' } },
        { name: 'role', type: 'enum', note: 'user | assistant | system' },
        { name: 'content', type: 'text' },
        { name: 'reactions', type: 'json', nullable: true },
        { name: 'created_at', type: 'timestamp' },
      ],
    },
    {
      id: 'squads', name: 'squads', label: '스쿼드', groupId: 'ops', icon: 'Users',
      description: '여러 에이전트 묶음 (도깨비스쿼드 등).',
      x: 1080, y: 80, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'name', type: 'text' },
        { name: 'agent_ids', type: 'json' },
      ],
    },
    {
      id: 'tasks', name: 'tasks', label: '태스크', groupId: 'ops', icon: 'FileText',
      description: '에이전트에게 배정되는 작업 단위.',
      x: 400, y: 440, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'agent_id', type: 'text', fk: { entity: 'agents' } },
        { name: 'squad_id', type: 'uuid', fk: { entity: 'squads' }, nullable: true },
        { name: 'title', type: 'text' },
        { name: 'status', type: 'enum', note: 'todo | in_progress | done' },
        { name: 'due_at', type: 'timestamp', nullable: true },
      ],
    },
    {
      id: 'domain_rules', name: 'domain_rules', label: '도메인 규칙', groupId: 'ops', icon: 'Tag',
      description: '에이전트별 검수 규칙. severity=error는 절대 위반 금지.',
      x: 740, y: 440, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'agent_id', type: 'text', fk: { entity: 'agents' } },
        { name: 'rule', type: 'text' },
        { name: 'severity', type: 'enum', note: 'error | warning' },
      ],
    },
    {
      id: 'feedback', name: 'feedback', label: '피드백', groupId: 'ops', icon: 'Bell',
      description: '검수/실행 결과 피드백 누적 (thumbs up/down).',
      x: 1080, y: 440, width: 240,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'agent_id', type: 'text', fk: { entity: 'agents' } },
        { name: 'type', type: 'enum' },
        { name: 'category', type: 'text' },
        { name: 'comment', type: 'text' },
        { name: 'created_at', type: 'timestamp' },
      ],
    },
  ],
  relationships: [
    { from: 'agents', to: 'sessions', type: 'one-to-many', label: 'has', color: '#1e3a8a',
      path: 'M 300 180 L 400 180', labelPos: { x: 350, y: 165 },
      explanation: '에이전트 하나가 여러 세션을 가질 수 있어요.' },
    { from: 'sessions', to: 'messages', type: 'one-to-many', label: 'contains', color: '#16a34a',
      path: 'M 640 180 L 740 180', labelPos: { x: 690, y: 165 },
      explanation: '세션 안에 여러 메시지가 들어있어요.' },
    { from: 'agents', to: 'tasks', type: 'one-to-many', label: 'has', color: '#d97706',
      path: 'M 180 220 C 180 340, 300 400, 400 480', labelPos: { x: 230, y: 360 },
      explanation: '에이전트에게 여러 태스크가 배정돼요.' },
    { from: 'agents', to: 'domain_rules', type: 'one-to-many', label: 'has', color: '#d97706',
      path: 'M 200 220 C 300 340, 600 400, 740 480', labelPos: { x: 450, y: 360 },
      explanation: '에이전트마다 지켜야 할 도메인 규칙 세트.' },
    { from: 'agents', to: 'feedback', type: 'one-to-many', label: 'receives', color: '#d97706',
      path: 'M 250 220 C 500 340, 900 400, 1080 480', labelPos: { x: 700, y: 360 },
      explanation: '에이전트에 대한 피드백이 누적돼요.' },
    { from: 'squads', to: 'tasks', type: 'one-to-many', label: 'contains', color: '#d97706',
      path: 'M 1200 220 L 600 460', labelPos: { x: 900, y: 380 },
      explanation: '스쿼드는 여러 태스크를 포함해요.' },
  ],
};
