import type { ERD } from '@/erd/types';

/**
 * Plick (playlist-editor) 데이터 모델 (MVP 계획안)
 * 현재 Plick은 브라우저 단일 페이지라 DB 미연동. 이 ERD는 계정 연동 + 서버 저장 도입 시의 목표 스키마.
 */
export const PLICK_ERD: ERD = {
  project: 'Plick',
  version: 0,
  updated: '2026-04-21',
  vision:
    '플레이리스트 영상 에디터의 저장/공유를 위한 데이터 모델. 현재는 브라우저 메모리만 사용. 향후 계정·프로젝트 저장·렌더 큐 도입 시 이 스키마로 확장.',
  canvas: { width: 1540, height: 760 },
  groups: [
    { id: 'user',    name: '사용자',   color: '#1e3a8a', accentBg: '#eff6ff', accentText: '#1e3a8a' },
    { id: 'content', name: '콘텐츠',   color: '#16a34a', accentBg: '#ecfdf5', accentText: '#15803d' },
    { id: 'output',  name: '출력',     color: '#d97706', accentBg: '#fffbeb', accentText: '#b45309' },
  ],
  entities: [
    {
      id: 'users',
      name: 'users',
      label: '사용자',
      groupId: 'user',
      icon: 'Users',
      description: '로그인 계정. 현재 signup API는 있으나 DB 미연동 상태.',
      x: 60, y: 80,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'email', type: 'text', unique: true },
        { name: 'password_hash', type: 'text' },
        { name: 'name', type: 'text' },
        { name: 'created_at', type: 'timestamp' },
      ],
    },
    {
      id: 'projects',
      name: 'projects',
      label: '프로젝트',
      groupId: 'user',
      icon: 'FileText',
      description: '한 개의 영상 편집 세션 = 플레이리스트 1개 + 설정.',
      x: 440, y: 80,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'user_id', type: 'uuid', fk: { entity: 'users' } },
        { name: 'title', type: 'text' },
        { name: 'layout', type: 'enum', note: 'classic | big-typo | neon ...' },
        { name: 'settings_json', type: 'json', note: 'EditorSettings 직렬화' },
        { name: 'updated_at', type: 'timestamp' },
      ],
    },
    {
      id: 'render_jobs',
      name: 'render_jobs',
      label: '렌더 작업',
      groupId: 'output',
      icon: 'Play',
      description: '영상 출력 큐. 브라우저 렌더 또는 GPU 클라우드 렌더.',
      x: 820, y: 80,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'project_id', type: 'uuid', fk: { entity: 'projects' } },
        { name: 'status', type: 'enum', note: 'pending | rendering | done | failed' },
        { name: 'output_url', type: 'text', nullable: true },
        { name: 'codec', type: 'enum', note: 'h264 | hevc | av1' },
        { name: 'resolution', type: 'text', note: '1920x1080 ...' },
        { name: 'completed_at', type: 'timestamp', nullable: true },
      ],
    },
    {
      id: 'templates',
      name: 'templates',
      label: '템플릿',
      groupId: 'user',
      icon: 'Tag',
      description: '저장된 프리셋. 설정을 다음 프로젝트에 재사용.',
      x: 1200, y: 80,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'user_id', type: 'uuid', fk: { entity: 'users' } },
        { name: 'name', type: 'text' },
        { name: 'settings_json', type: 'json' },
        { name: 'created_at', type: 'timestamp' },
      ],
    },
    {
      id: 'tracks',
      name: 'tracks',
      label: '트랙',
      groupId: 'content',
      icon: 'Play',
      description: '플레이리스트의 개별 곡. 오디오 파일 + 메타 + 자막 동기화 대상.',
      x: 440, y: 460,
      width: 260,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'project_id', type: 'uuid', fk: { entity: 'projects' } },
        { name: 'position', type: 'int' },
        { name: 'name', type: 'text' },
        { name: 'artist', type: 'text' },
        { name: 'duration', type: 'float' },
        { name: 'trim_start', type: 'float', nullable: true },
        { name: 'trim_end', type: 'float', nullable: true },
        { name: 'audio_url', type: 'text' },
        { name: 'bg_image_url', type: 'text', nullable: true },
      ],
    },
    {
      id: 'subtitles',
      name: 'subtitles',
      label: '자막',
      groupId: 'content',
      icon: 'FileText',
      description: '트랙 단위 자막 세그먼트 (Whisper forced-align 결과).',
      x: 880, y: 460,
      width: 260,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'track_id', type: 'uuid', fk: { entity: 'tracks' } },
        { name: 'segment_index', type: 'int' },
        { name: 'start', type: 'float' },
        { name: 'end', type: 'float' },
        { name: 'text', type: 'text' },
      ],
    },
  ],
  relationships: [
    {
      from: 'users', to: 'projects',
      type: 'one-to-many', label: 'has',
      color: '#1e3a8a',
      path: 'M 300 180 L 440 180',
      labelPos: { x: 370, y: 165 },
      explanation: '한 사용자가 여러 프로젝트를 가질 수 있어요.',
    },
    {
      from: 'projects', to: 'render_jobs',
      type: 'one-to-many', label: 'generates',
      color: '#d97706',
      path: 'M 680 180 L 820 180',
      labelPos: { x: 750, y: 165 },
      explanation: '프로젝트 하나가 여러 번의 렌더 작업을 만들어낼 수 있어요.',
    },
    {
      from: 'users', to: 'templates',
      type: 'one-to-many', label: 'has',
      color: '#1e3a8a',
      path: 'M 300 120 C 700 40, 900 40, 1200 120',
      labelPos: { x: 760, y: 40 },
      explanation: '한 사용자가 여러 템플릿을 저장할 수 있어요.',
    },
    {
      from: 'projects', to: 'tracks',
      type: 'one-to-many', label: 'contains',
      color: '#16a34a',
      path: 'M 560 280 L 560 460',
      labelPos: { x: 560, y: 370 },
      explanation: '하나의 프로젝트(플레이리스트)는 여러 트랙을 포함해요.',
    },
    {
      from: 'tracks', to: 'subtitles',
      type: 'one-to-many', label: 'has',
      color: '#16a34a',
      path: 'M 700 580 L 880 580',
      labelPos: { x: 790, y: 565 },
      explanation: '트랙 하나가 여러 자막 세그먼트를 가져요 (Whisper 결과).',
    },
  ],
};
