import type { Roadmap } from './types';

export const ROADMAP: Roadmap = {
  project: 'SEON Hub',
  version: 1,
  updated: '2026-04-20',
  vision:
    '내 모든 개인 프로젝트의 상태·디자인·로드맵을 단일 허브에서 본다. 팀용 ERP가 아닌 1인 운영자용 DAM+ERP 하이브리드. 클로드 협업을 전제로 한 구조 — Claude가 한 파일만 읽으면 지금 뭘 해야 하는지 알 수 있게.',
  currentPhaseId: 'p2-design-system',
  phases: [
    {
      id: 'p1-foundation',
      title: '기반 구축',
      status: 'done',
      start: '2026-03-01',
      end: '2026-04-17',
      summary: 'Next.js 16 + Supabase + 사이드바 레이아웃 + 핵심 도메인 CRUD',
      goal: '로그인부터 프로젝트·회차·클라이언트·파트너·지출 CRUD까지 완료',
      items: [
        { title: 'Next.js 16 App Router 셋업', status: 'done' },
        { title: 'Supabase auth + middleware', status: 'done' },
        { title: '사이드바(아이콘 레일 + 패널)', status: 'done' },
        { title: '프로젝트·회차 CRUD', status: 'done' },
        { title: '클라이언트·파트너 CRUD', status: 'done' },
        { title: '지출/정산 기본 CRUD', status: 'done' },
        { title: '매니지먼트 탭(메인/미기입/리포트)', status: 'done' },
      ],
      wireframes: ['login', 'dashboard', 'projects', 'management'],
    },
    {
      id: 'p2-design-system',
      title: '디자인 시스템 + 드릴인',
      status: 'in-progress',
      start: '2026-04-18',
      target: '2026-05-05',
      summary: '토큰·primitive·wireframes·드릴인·로드맵까지 프로젝트 내부 자체 완결',
      goal: '/design /wireframes /dev/[id] /roadmap 네 라우트가 전부 자체 완결 + 외부 kit 의존 없음',
      items: [
        { title: 'src/design/tokens.css 분리', status: 'done' },
        { title: 'primitive 10개 (Button/Input/Textarea/Select/Checkbox/Tabs + 기존 4)', status: 'done' },
        { title: '/design 쇼케이스 페이지', status: 'done' },
        { title: 'src/design/README.md 규약', status: 'done' },
        { title: '실제 SEON Hub 와이어프레임 5개 (login/dashboard/projects/management/dev-workspace)', status: 'done' },
        { title: '/wireframes 좌측메뉴+우측프리뷰 분할뷰', status: 'done' },
        { title: '/dev/[id] 드릴인 페이지 + 탭 (개요/디자인/와이어프레임)', status: 'done' },
        { title: 'Dev Workspace 카드 클릭 → 드릴인', status: 'done' },
        { title: '로드맵 시스템 (타입 + 데이터 + 뷰 + 라우트 + 드릴인 탭)', status: 'done' },
        { title: '구 /settings/design/components 페이지 정리 또는 삭제', status: 'done', note: '/design으로 href 변경 후 폴더 삭제' },
        { title: '로드맵 플로우 다이어그램 뷰 + 페이즈↔wireframe 매핑', status: 'done', note: 'RoadmapFlowView + RoadmapView 내부 토글, 페이즈마다 wireframe 칩' },
        { title: '로드맵 플로우를 세로 교차 타임라인(Variant C)으로 재작성', status: 'done' },
        { title: 'ERD 시스템 (types + data + ERDView + /erd + 드릴인 탭 + API hasERD)', status: 'done', note: 'Variant C2 · 도트 그리드 + 베지어 + crow\'s foot + 도메인 색' },
      ],
      wireframes: ['dev-workspace'],
    },
    {
      id: 'p3-automation',
      title: '자동화 + 리마인더',
      status: 'planned',
      target: '2026-06-30',
      summary: '반복 작업 자동화 (미기입 알림, 정산 리포트, Slack 알림)',
      goal: '매주 수동으로 하던 정리를 자동화로 대체',
      items: [
        { title: '매주 미기입 자동 알림 (Slack)', status: 'todo' },
        { title: '월 정산 리포트 자동 생성', status: 'todo' },
        { title: '데드라인 24h 전 알림', status: 'todo' },
        { title: '주간 리포트 메일', status: 'todo' },
      ],
    },
    {
      id: 'p4-integration',
      title: '통합 + 다른 프로젝트 확산',
      status: 'planned',
      target: '2026-08-31',
      summary: 'arc-v2 연결 검토, 디자인 시스템을 다른 프로젝트에도 이식',
      goal: '비모 ERP·Plick·music-assist에도 roadmap·design·wireframes 템플릿 적용',
      items: [
        { title: 'arc-v2 통합 여부 결정', status: 'todo' },
        { title: '비모 ERP에 src/design·src/roadmap 이식', status: 'todo' },
        { title: 'Plick·music-assist 동일 적용', status: 'todo' },
        { title: '스타터 템플릿 저장소 생성', status: 'todo' },
      ],
    },
    {
      id: 'p5-mobile',
      title: '모바일 대응',
      status: 'deferred',
      target: '미정',
      summary: '필요성 검증 후 결정 — 현재는 PC-first 운영으로 충분',
      goal: '모바일에서도 최소 회차 입력·미기입 확인 가능',
      items: [
        { title: '모바일 필요성 검증 (실사용 시나리오 수집)', status: 'todo' },
        { title: 'PWA 인스톨 개선', status: 'todo' },
        { title: '핵심 화면만 반응형 튜닝', status: 'todo' },
      ],
    },
  ],
  decisions: [
    {
      date: '2026-04-19',
      title: '로드맵을 src/roadmap/roadmap.ts 단일 TS 파일로',
      why: 'GUI 렌더·Claude 파싱·에디터 자동완성·Git 히스토리 네 마리 토끼를 한 형식으로 잡음',
      alt: 'YAML 프론트매터 + md / JSON / DB 테이블 — 각각 한두 축에서 부족',
    },
    {
      date: '2026-04-19',
      title: '와이어프레임은 저가공 박스가 아니라 실제 시각 목업',
      why: '사용자가 "실제 보여지는 디자인"을 원했고, 화면 간 일관성 검증에도 실제 톤이 더 유용',
      alt: '추상 박스 wireframe — 빠르지만 실제 앱과 동떨어져 가치 낮음',
    },
    {
      date: '2026-04-19',
      title: 'Dev Workspace 카드 클릭 → /dev/[id] 드릴인 (외부 탭 X)',
      why: '"들어가서 확인"하는 UX. 외부 탭 점프는 맥락 끊김',
      alt: '외부 localhost:<port>/design 새 탭 열기 — 다른 프로젝트에는 여전히 사용',
    },
    {
      date: '2026-04-19',
      title: 'hype5 ERP → SEON Hub 리브랜딩 (UI만)',
      why: '개인용 Hub 성격 강해짐. 디렉토리명·DB·env는 기존 유지 (마이그 부담)',
      alt: '전면 이름 교체 (hype5-erp → seon-hub 디렉토리 rename)',
    },
    {
      date: '2026-04-19',
      title: '모든 개인 프로젝트를 ~/Desktop/Dev/ 아래로 통합',
      why: '루트 직속 13개 디렉토리가 혼란. Dev Workspace 스캔 대상 단일화',
      alt: '각 프로젝트 경로 각자 유지 — 산발적 관리 계속',
    },
    {
      date: '2026-04-18',
      title: '각 프로젝트가 자체 src/design·src/wireframes·src/roadmap 보유',
      why: '외부 kit 의존 없이 자체 완결. AI 협업 시 한 폴더 안에서 완결되게',
      alt: '@seon/ui npm 패키지 — 버저닝·배포·동기화 부담',
    },
  ],
  openQuestions: [
    'arc-v2(넥스트캠프)와 통합할지, 별개로 둘지',
    '모바일 대응을 언제 어디까지 할지',
    '외부 팀/파트너 계정 접근을 허용할지 (현재는 내부 전용)',
    '매니지먼트 미기입 판별 규칙을 프로젝트 타입별로 다르게 할지',
  ],
  risks: [
    {
      title: '마이그레이션으로 인한 데이터 유실',
      mitigation: 'CREATE TABLE IF NOT EXISTS 강제, DROP TABLE 금지, 매일 백업, note 테이블 감사 트리거',
      severity: 'high',
    },
    {
      title: '기능 범위 무한 확장',
      mitigation: '페이즈당 3~4주 캡, todo는 phase.items 배열 초과 시 다음 페이즈로 미룸',
      severity: 'med',
    },
    {
      title: '디자인 시스템 drift',
      mitigation: '새 UI는 반드시 primitive 조합으로. 하드코딩 색 금지 (README 규약)',
      severity: 'low',
    },
  ],
};
