import type { ERD } from './types';

export const ERD: ERD = {
  project: 'SEON Hub',
  version: 1,
  updated: '2026-04-20',
  vision:
    '데이터 모델 단일 소스. Claude가 수정 전 ERD 먼저 읽어 관계·FK 이해하고 안전하게 작업. 사람은 도메인 구조를 한눈에 파악.',
  canvas: { width: 1280, height: 600 },
  groups: [
    { id: 'content',  name: '콘텐츠', color: '#1e3a8a', accentBg: '#eff6ff', accentText: '#1e3a8a' },
    { id: 'finance',  name: '재무',   color: '#16a34a', accentBg: '#ecfdf5', accentText: '#15803d' },
    { id: 'partner',  name: '파트너', color: '#d97706', accentBg: '#fffbeb', accentText: '#b45309' },
  ],
  entities: [
    {
      id: 'clients',
      name: 'clients',
      label: '클라이언트',
      groupId: 'content',
      icon: 'Users',
      description: '프로젝트를 의뢰하는 고객사/담당자',
      x: 60, y: 60,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'name', type: 'text' },
        { name: 'contact_person', type: 'text', nullable: true },
        { name: 'email', type: 'text', nullable: true },
        { name: 'status', type: 'enum' },
      ],
    },
    {
      id: 'projects',
      name: 'projects',
      label: '프로젝트',
      groupId: 'content',
      icon: 'Briefcase',
      description: '영상·개발·콘텐츠 프로젝트',
      x: 360, y: 60,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'client_id', type: 'uuid', fk: { entity: 'clients' } },
        { name: 'title', type: 'text' },
        { name: 'type', type: 'enum', note: 'video | dev | content' },
        { name: 'status', type: 'enum' },
      ],
    },
    {
      id: 'episodes',
      name: 'episodes',
      label: '회차',
      groupId: 'content',
      icon: 'Play',
      description: '프로젝트를 구성하는 회차/에피소드',
      x: 660, y: 60,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'project_id', type: 'uuid', fk: { entity: 'projects' } },
        { name: 'episode_number', type: 'int' },
        { name: 'title', type: 'text' },
        { name: 'deadline', type: 'date', nullable: true },
      ],
    },
    {
      id: 'partners',
      name: 'partners',
      label: '파트너',
      groupId: 'partner',
      icon: 'UserPlus',
      description: '외부 프리랜서·협업 파트너',
      x: 960, y: 60,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'name', type: 'text' },
        { name: 'partner_type', type: 'enum' },
        { name: 'role', type: 'enum' },
      ],
    },
    {
      id: 'expenses',
      name: 'expenses',
      label: '지출',
      groupId: 'finance',
      icon: 'Receipt',
      description: '프로젝트별 지출 내역',
      x: 360, y: 380,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'project_id', type: 'uuid', fk: { entity: 'projects' } },
        { name: 'amount', type: 'int' },
        { name: 'category', type: 'enum' },
      ],
    },
    {
      id: 'partner_settlements',
      name: 'partner_settlements',
      label: '파트너 정산',
      groupId: 'finance',
      icon: 'CreditCard',
      description: '파트너 단위 정산 기록',
      x: 810, y: 380,
      width: 260,
      fields: [
        { name: 'id', type: 'uuid', pk: true },
        { name: 'partner_id', type: 'uuid', fk: { entity: 'partners' } },
        { name: 'episode_id', type: 'uuid', fk: { entity: 'episodes' } },
        { name: 'amount', type: 'int' },
        { name: 'status', type: 'enum' },
      ],
    },
  ],
  relationships: [
    {
      from: 'clients', to: 'projects',
      type: 'one-to-many', label: 'has',
      color: '#1e3a8a',
      path: 'M 300 160 C 330 160, 330 160, 360 160',
      labelPos: { x: 330, y: 145 },
    },
    {
      from: 'projects', to: 'episodes',
      type: 'one-to-many', label: 'contains',
      color: '#1e3a8a',
      path: 'M 600 160 C 630 160, 630 160, 660 160',
      labelPos: { x: 630, y: 145 },
    },
    {
      from: 'projects', to: 'expenses',
      type: 'one-to-many', label: 'incurs',
      color: '#16a34a',
      path: 'M 480 280 C 480 325, 480 325, 480 380',
      labelPos: { x: 480, y: 330 },
    },
    {
      from: 'episodes', to: 'partner_settlements',
      type: 'one-to-many', label: 'generates',
      color: '#16a34a',
      path: 'M 780 280 C 780 320, 840 320, 880 380',
      labelPos: { x: 830, y: 325 },
    },
    {
      from: 'partners', to: 'partner_settlements',
      type: 'one-to-many', label: 'receives',
      color: '#d97706',
      path: 'M 1080 280 C 1080 320, 1020 340, 980 380',
      labelPos: { x: 1040, y: 325 },
    },
  ],
};
